page:
  author: Florian Kasper
  encoding: utf-8
  logo: "layout/logo_top.png"
  
#!!!!!!!#!!!!!!!!!!!!#!!!!!!!!!!!!!!!#!!!!!!!!!!!!!!!!
######## ############ ############### ################  
## DO NOT CHANGE UNLESS YOU KNOW WHAT YOU ARE DOING ##
######## ############ ############### ################
#!!!!!!!#!!!!!!!!!!!!#!!!!!!!!!!!!!!!#!!!!!!!!!!!!!!!!
roles:
  moderate: moderate_global
  delete: del_global
  update: update_global
  rename: rename_global
  ban: ban_global
  admin: administrator
  
  #on own account
  account:
    moderate: mod_account
    delete: del_account
    update: update_account
    rename: rename_account
    ban: ban_account
  book:
    create: create_book
    new: new_book