page:
  author: Florian Kasper
  encoding: utf-8
  logo: "layout/logo_top.png"
  
#!!!!!!!#!!!!!!!!!!!!#!!!!!!!!!!!!!!!#!!
## WICH ATTRS A NEW USER SHOULD HAVE? ##
#!!!!!!!#!!!!!!!!!!!!#!!!!!!!!!!!!!!!#!!
newuser:
  roles:
      - search
      - tags.menu
      - books.menu
      - authors.menu
      - home.menu
      - genres.menu
      - book.view
      - author.view
      - tag.view
      - genre.view
    
#!!!!!!!#!!!!!!!!!!!!#!!!!!!!!!!!!!!!#!!!!!!!!!!!!!!!!
######## ############ ############### ################  
## DO NOT CHANGE UNLESS YOU KNOW WHAT YOU ARE DOING ##
######## ############ ############### ################
#!!!!!!!#!!!!!!!!!!!!#!!!!!!!!!!!!!!!#!!!!!!!!!!!!!!!!
roles:
  globally:
      search: search_global
    
  search: search_global
  moderate: moderate_global
  delete: del_global
  update: update_global
  rename: rename_global
  ban: ban_global
  admin: administrator
  menu:
    home: home_menu_link
    books: books_menu_link
    authors: authors_menu_link
    genres: genres_menu_link
    tags: tags_menu_link
  #on own account
  account:
    moderate: mod_account
    delete: del_account
    update: update_account
    rename: rename_account
    ban: ban_account
  book:
    create: create_book
    new: new_book