image:
    max_filesize: 2048
    thumb: 100x100#
    small: 150x150>
    medium: 400x400
    large: 1920x1080
    thumb_quality: 75
   
      
tags:
    maxresults: 100
user:
    allow_registration: true
    allow_login: true
    allow_profile_view: true